name: Frontend CI
on:
  push:
    branches:
      - develop
      - main
jobs:
  deploy:
    name: Pull latest updates
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.4.1
      uses: actions/setup-node@v4
      with:
        node-version: 22.4.1

    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        node-version: 22.4.1
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd FrontendVue
          sudo git stash
          sudo git pull
          sudo n 22.4.1
          sudo chmod +x build.sh
          sudo ./build.sh
          sudo systemctl daemon-reload
          sudo systemctl reload nginx

  send_message:
    name: Send success message
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен.
