name: Frontend CI
on:
  push:
    branches:
      - develop
      - main
jobs:
  deploy:
    name: Pull latest updates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/${{ secrets.USER }}/FrontendVue
          echo ${{ secrets.PASSWORD }} | sudo -S git stash
          echo ${{ secrets.PASSWORD }} | sudo -S git pull
          echo ${{ secrets.PASSWORD }} | sudo -S chmod +x build.sh
          echo ${{ secrets.PASSWORD }} | sudo -S su -c ./build.sh ${{ secrets.USER }}
          echo ${{ secrets.PASSWORD }} | sudo -S systemctl reload nginx

  send_message:
    name: Send success message
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен.
